### ISSUE TITLE
How can I send a YAML file to a URL(nodejs server) via a POST request using RestClient?

### ISSUE THREAD

**Issue by knightcube** [proyecto26/RestClient#144]
The generic code in the official README is great but I am trying to figure out how to send the YAML file. If I find the file by filename in C#, how do I upload it to my node.js server by modifying that generic code?

**Comment by HtDreams** [comment]
Hi!

I'm also struggling with this task. I love how easy and simple is to use RestClient, but after several days I didn't managed to send an image file to my REST API (i'm using apache and PHP for that).

I have the REST API method working and tested from Postman, without any problem, but i've tried several things from unity and all of them fails at server with the following error:

[Tue Jul 28 09:44:18.620998 2020] [:error] [pid 21536:tid 140213409462016] [client 47.59.42.252:40698] [client 47.59.42.252] ModSecurity: Access denied with code 403 (phase 2). Match of "eq 0" against "MULTIPART_STRICT_ERROR" required. [file "/etc/modsecurity/12_HTTP_Protocol.conf"] [line "30"] [id "210240"] [rev "4"] [msg "WAF: Multipart request body failed strict validation: PE 0, BQ 1, BW 0, DB 1, DA 0, HF 0, LF 0, SM , IQ 0, IH 0, FLE 0||api.boulebarfun.com|F|2"] [severity "CRITICAL"] [tag "CWAF"] [tag "Protocol"] [hostname "api.boulebarfun.com"] [uri "/v1/tickets/qr/42"] [unique_id "Xx-XUlJihFEAAFQgXRIAAABB"]

This is my unity code:

`				
string tid = _QRuploadID.ToString();
List<UnityEngine.Networking.IMultipartFormSection> formData = new List<UnityEngine.Networking.IMultipartFormSection>();
formData.Add(new UnityEngine.Networking.MultipartFormDataSection(
    "attributes",
    "{\"title\":\"" + tid + "\",\"filename\":\"" + tid + "\"}",
    "application/json"));
formData.Add(new UnityEngine.Networking.MultipartFormFileSection(
    "imagefile", 
    _QRbytes, // this is a byte[] with a jpg image already prepared
    tid+".jpg",
    "image/jpeg"));
_currentRequest = new RequestHelper
{
    Uri = _basePath + "tickets/qr/" + tid,
    Method = "POST",
    FormSections = formData,
    EnableDebug = true
};
RestClient.Request<Models.Response>(_currentRequest).Then(res =>
{
    _QRuploadID = -1;
    Array.Resize(ref _QRbytes, 0);
    callback?.Invoke(ErrorCodes.NO_ERROR, ""); // this method is passed a callback function to continue after the calls completes
}).Catch(err =>{
    // ERROR HANDLING CODE...
});
`

I've tried also generating the boundary, to add the content-type data, but without success... 
I've also tried passing WWWForm instead of FormSection, but also same error

Any clues?

**Comment by jdnichollsc** [comment]
Did you try using [UnityWebRequest](https://docs.unity3d.com/Manual/UnityWebRequest.html), remember this asset is just a wrapper for that system, most of the time used for REST APIs sending/receiving JSON data :)
PD: If using **UnityWebRequest** directly works as expected, please share the code to see what's the difference using this asset

**Comment by knightcube** [comment]
I tried using UnityWebRequest and have provided the code below. I have also pointed out the line in which the error is occurring. Why is the file.downloadHandler null? Am I missing something?
```
 public void PostYaml(){
		string uploadYamlURL = "http://localhost:3000/upload-yaml";

		string directoryPath = Path.Combine(Application.persistentDataPath, "YAML");
		UnityWebRequest file = new UnityWebRequest();
		WWWForm form = new WWWForm();
		Debug.Log(file);
		Debug.Log(file.downloadHandler); // Null Reference Error in this line
		Debug.Log(directoryPath);
		Debug.Log(Path.GetFileName(directoryPath));
		form.AddBinaryData("yaml",file.downloadHandler.data,Path.GetFileName(directoryPath));
                UnityWebRequest req = UnityWebRequest.Post(uploadYamlURL, form);      
}
```

**Comment by knightcube** [comment]
```
public void PostYaml()
	{
		string uploadYamlURL = "http://localhost:3000/upload-yaml";
		string directoryPath = Application.dataPath+ "/YAML";

                // Was testing something else (not required)
		/*
                WWW localFile = new WWW("file:///" + "image.png");
		if (localFile.error == null)
			Debug.Log("Loaded file successfully");
		else
		{
			Debug.Log("Open file error: " + localFile.error);
		}
                */

		UnityWebRequest file = new UnityWebRequest();
		DownloadHandlerBuffer dH = new DownloadHandlerBuffer();
		file.downloadHandler = dH;
		file.SetRequestHeader("Content-Type", "multipart/form-data");

		WWWForm form = new WWWForm();
		form.AddBinaryData("yaml", file.downloadHandler.data, "something.yaml");
		
		UnityWebRequest req = UnityWebRequest.Post(uploadYamlURL, form);
		req.SendWebRequest();

		if (req.error != null)
		{
			Debug.Log("Error" + req.error);
		}
		else
		{
			Debug.Log("Done!" + req.downloadHandler.text);
		}
```

**Comment by jdnichollsc** [comment]
Awesome, following your code with this asset:
```csharp
UnityWebRequest file = new UnityWebRequest();
DownloadHandlerBuffer dH = new DownloadHandlerBuffer();
file.downloadHandler = dH;
file.SetRequestHeader("Content-Type", "multipart/form-data");

WWWForm form = new WWWForm();
form.AddBinaryData("yaml", file.downloadHandler.data, "something.yaml");
var currentRequest = new RequestHelper
{
  Uri = uploadYamlURL,
  Method = "POST",
  FormSections = formData,
  EnableDebug = true,
  ContentType = "multipart/form-data", // Here you can attach a UploadHandler/DownloadHandler too :)
  FormData = form
}
RestClient.Request(currentRequest)
  .Then(res => Debug.Log("Done!"))
  .Catch(err => Debug.Log("Error" + err));
```

Regards
