### ISSUE TITLE
Stupid question, but what is the recommended way to return a value from a method?

### ISSUE THREAD

**Issue by MeltdownInteractive** [proyecto26/RestClient#247]
All the code examples have void as the return type.

But I would like to create some of my methods that make a REST API call return a value. 
What is the recommended method to do this with this Promise based library considering it doesn't support async/await?

I'm thinking of just having one of my method params being an Action

i.e 

```
public void Post(string param1, Action<bool, string> callback)
        {

            RestClient.Post<Post>(currentRequest)

                .Then(result =>

                {

                    callback(true, JsonUtility.ToJson(result, true));

                })

                .Catch(err => callback(false, err.Message));
        }
```

**Comment by maifeeulasad** [comment]
I would recommend doing something like this:
```
public void Post(string param1, Action<bool, string> callback)
{
    RestClient.Post<Post>(currentRequest)
        .Then(result => callback(true, JsonUtility.ToJson(result, true)))
        .Catch(err => callback(false, err.Message));
}
```

Feel free to reach out. I wasn't available for quite a while, and I'm extremely sorry for that.

One helpful link: https://github.com/proyecto26/RestClient/blob/efcbcf4f9c85ffcb81c5924d8d0243a53c8a0caa/demo/Assets/MainScript.cs

I hope this answers your question, but otherwise I am open for a discussion.
