### ISSUE TITLE
RequestHelper.CertificateHandler missing?

### ISSUE THREAD

**Issue by natwales** [proyecto26/RestClient#51]
Looking at the documentation it looks like I should be able to set a custom CertificateHandler as a property of the RequestHelper. There appears to be a mismatch with the actual API in release 2.4.1 as there is no definition for a CertificateHandler property.

**Comment by jdnichollsc** [comment]
Unfortunately that's a Unity limitation: DLLs can't be mapped to .NET framework versions currently and the same issue applies for the Unity version, so my recommendation is to copy the source code of the library (only the .cs files) instead of use the `.dll` generated from `NuGet` https://github.com/proyecto26/RestClient/tree/master/src/Proyecto26.RestClient

**Comment by jdnichollsc** [comment]
@Arvtesh #RoryDungan @ashleydavis hello guys, you have a better experience with Unity, Do you know if exist a better way to fix that Unity issue? I'm publishing to NuGet from Azure DevOps

**Comment by jdnichollsc** [comment]
@Arvtesh @RoryDungan @ashleydavis hello guys, sorry to tag you
You have a better experience with Unity, Do you know if exist a better way to fix that Unity issue? I'm publishing to NuGet from Azure DevOps
Thanks in advance,
Juan

**Comment by jdnichollsc** [comment]
@natwales let me publish a new version **2.5.2** with the source code from the [Unity Asset Store](https://assetstore.unity.com/packages/tools/network/rest-client-for-unity-102501)

**Comment by RoryDungan** [comment]
I'm guessing that `UNITY_2018_1_OR_NEWER` wasn't defined when you built the DLL? That's not really a Unity issue but yeah you're right there isn't a way to distribute different versions of a DLL for different Unity versions. You'd have to rebuild the DLL with that defined.

**Comment by RoryDungan** [comment]
Potentially you could try disabling functionality that doesn't work in older versions of Unity at runtime using [Application.unityVersion](https://docs.unity3d.com/ScriptReference/Application-unityVersion.html) instead of conditionally compiling sections with preprocessor directives. That wouldn't work for something like enabling or disabling a whole property though.

**Comment by jdnichollsc** [comment]
@RoryDungan Thanks for your help, it's really appreciated!

**Comment by jdnichollsc** [comment]
@natwales thanks for report this issue, now you can find the source code of the library from the `RestClient.unitypackage` file (and from the Unity Asset Store) instead of use the `Proyecto26.RestClient.dll` 👍
