### ISSUE TITLE
Scene reload issue

### ISSUE THREAD

**Issue by gevorg-gevp** [proyecto26/RestClient#8]
Hi guys,
We use RestClient in our project and stuck to following problem.
As far as we understood when client is making call  new Gameobject "StaticCoroutineRestClient " is created.
And it happens that if we load another scene during the call that game object is destroyed and we receive no response.
Is there any solutions or workaround to that problem?
Thanks.

**Comment by davidorbelian** [comment]
@gevorg-gevp @jdnichollsc 
May be https://github.com/proyecto26/RestClient/blob/master/src/Proyecto26.RestClient/Utils/StaticCoroutine.cs#L15-L18

    if (_runner == null)
    {
        _runner = new GameObject("Static Corotuine RestClient").AddComponent<CoroutineHolder>();
    }

with something like

    if (_runner == null)
    {
        _runner = new GameObject("Static Corotuine RestClient").AddComponent<CoroutineHolder>();
        Object.DontDestroyOnLoad(_runner);
    }

But it is potentially unsafe, because you can have some references in the callback to objects from the scene you are unloading. It should be tested.

**Comment by jdnichollsc** [comment]
@davidorbelian Adding the `DontDestroyOnLoad` to prevent this issue, please let me know any other issue

**Comment by jdnichollsc** [comment]
@gevorg-gevp check the last release and let me know! 👍 https://github.com/proyecto26/RestClient/releases/tag/1.2.2
